name: test
on: [push, pull_request]
jobs:
  dogfood:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with: { python-version: '3.11' }

    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Install requirements
      run: uv pip install --system mypy

    - name: Setup Git user
      run: |
        git config --global user.email "report-new-linter-errors@mail.invalid"
        git config --global user.name "report-new-linter-errors"
    - name: Run report-new-linter-errors with mypy, then save the snapshot
      run: |
        set +e # Keep going even if the command fails, so we can commit the new snapshot
        make
        python report-new-linter-errors mypy report_new_linter_errors.py
        exit_code=$?
        git add .report-new-linter-errors/
        git commit -m "Update report-new-linter-errors snapshot"
        git push
        exit $exit_code

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/ruff-action@v3
      with: { args: '--version' }
    - run: ruff format --diff report_new_linter_errors.py test.py
    - run: ruff check --diff report_new_linter_errors.py test.py

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with: { python-version: '3.11' }
    - run: python test.py
